### ISSUE TITLE
Highlight breaks lines with <br>

### ISSUE THREAD

**Issue by HoffmannP** [wcoder/highlightjs-line-numbers.js#25]
It seems to me that highlight.js now breaks lines with `<br>` instead of leaving the lines as they are.

**Comment by wcoder** [comment]
Hi @HoffmannP, thanks for the feedback!

Which version of highlight.js do you use?

For better understanding your issue, could you please add a screenshot or link to an example?

**Comment by RafaelMFonseca** [comment]
I can confirm its true.
Its break with this filter on wordpress:
`function automatic_newline($content) {
    return str_replace(array("\r\n", "\r", "\n"), "<br />", $content);
}
add_filter('the_content', 'automatic_newline', 99);
add_filter('the_excerpt', 'automatic_newline', 99);`

**Comment by wcoder** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/wcoder/highlightjs-line-numbers.js/releases). You can also contribute directly by providing a patch. :)

Thank you!
