### ISSUE TITLE
it does not work as you show

### ISSUE THREAD

**Issue by Theolodewijk** [wcoder/highlightjs-line-numbers.js#58]
I get numpers in separate tables, I use the latest bootstrap version

```
    <script src="<?=$siteurl?>/highlight/highlight.pack.js"></script>
    <script src="<?=$siteurl?>/highlight/highlightjs-line-numbers.min.js"></script>
    <script>hljs.initHighlightingOnLoad();hljs.initLineNumbersOnLoad();</script>

    <style type="text/css">
    pre.directadmin {
        border: 1px solid #57aded;
        border-left: 10px solid #358ccb;
        border-radius: 4px;    
        text-align: left;
        padding-right: 5px;
    }
    </style>

<div class="common">
    <pre class="directadmin">
        <code class="bash"><?=$select_directadmin->content?></code>
    </pre>
</div>
```

Output of $select_directadmin->content == 

yum check-update
yum -y update
cd /usr/local/directadmin/custombuild
./build update
./build versions
./build update_versions

**Comment by wcoder** [comment]
Hi @Theolodewijk could you provide more info (output html or anything else) ?

**Comment by wcoder** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/wcoder/highlightjs-line-numbers.js/releases). You can also contribute directly by providing a patch. :)

Thank you!
