### ISSUE TITLE
Bad format show style

### ISSUE THREAD

**Issue by truefriend-cz** [wcoder/highlightjs-line-numbers.js#59]
Problem 1:
Code text isnt on one line. (with options "singleLine: true" too).
Missing effect as "white-space: pre;".

Problem 2:
And problem geting original style from highlight.min.js (font size and font-family).

Version 2.6.0

Do you can fixed, please?

Edit: Problem 1 has been fixed after add CSS this:
```
.hljs-ln .hljs-ln-line {
     white-space: pre;
}
```

**Comment by wcoder** [comment]
Hi @truefriend-cz thanks for the feedback!

Could you provide more info (used snippet or screenshot) about your problems?

**Comment by wcoder** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/wcoder/highlightjs-line-numbers.js/releases). You can also contribute directly by providing a patch. :)

Thank you!
