### ISSUE TITLE
pre formatting deleted when applied

### ISSUE THREAD

**Issue by yenrabbyui** [wcoder/highlightjs-line-numbers.js#64]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wcoder** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/wcoder/highlightjs-line-numbers.js/releases). You can also contribute directly by providing a patch. :)

Thank you!
